version: "3.7"

services:
  nodejs:
    container_name: nodejs
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      target: prod
      dockerfile: nodejs.dockerfile
    volumes:
      - .:/app
      - /app/dist
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env.docker
